In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

import matplotlib.pyplot as plt
import matplotlib.mlab as mlab            # The functions in this package can add the fitting curve of the random variable distribution
import numpy as np
from functions import *
from sklearn import decomposition
from sklearn import preprocessing

import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

import statsmodels.formula.api as smf
import statsmodels.api as sm

# Importation de la fonction function.py

In [2]:
data = pd.read_csv("notes.csv", sep=",")
data

is_genuine  diagonal  height_left  height_right  margin_low  margin_up  \
0          True    171.81       104.86        104.95        4.52       2.89   
1          True    171.67       103.74        103.70        4.01       2.87   
2          True    171.83       103.76        103.76        4.40       2.88   
3          True    171.80       103.78        103.65        3.73       3.12   
4          True    172.05       103.70        103.75        5.04       2.27   
..          ...       ...          ...           ...         ...        ...   
165       False    172.11       104.23        104.45        5.24       3.58   
166       False    173.01       104.59        104.31        5.04       3.05   
167       False    172.47       104.27        104.10        4.88       3.33   
168       False    171.82       103.97        103.88        4.73       3.55   
169       False    171.96       104.00        103.95        5.63       3.26   

     length  
0    112.83  
1    113.29  
2    113.84  
3    113.63  
4    113.55  
..      ...  
165  111.78  
166  110.91  
167  110.68  
168  111.87  
169  110.96  

[170 rows x 7 columns]

In [3]:
data_reg = data[["diagonal","height_left","height_right","margin_low","margin_up","length"]]

In [4]:
# Variables explicatives
x = data_reg
# variables à expliquer
y = data.is_genuine

In [5]:
import sklearn
from sklearn import preprocessing, decomposition, metrics
from sklearn.cluster import KMeans
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_validate, cross_val_score
from sklearn.metrics import confusion_matrix, classification_report
print(sklearn.__version__)

0.24.1


In [6]:
import os
os.makedirs('graph', exist_ok=True)

In [7]:
# Partition du jeu de données
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

In [8]:
# Régression logistique
reg_log = LogisticRegression(solver='liblinear')
reg_log.fit(x_train, y_train)

# Sauvegarde de prédictions
y_pred = reg_log.predict(x_test)
y_pred

array([False, False,  True,  True, False, False, False, False,  True,
       False,  True,  True,  True, False,  True, False,  True, False,
        True, False,  True, False, False, False, False,  True, False,
        True,  True,  True,  True,  True, False, False,  True, False,
        True, False,  True,  True,  True,  True, False])

In [9]:
matr_conf = metrics.confusion_matrix(y_test, y_pred)
matr_conf = pd.DataFrame(matr_conf)
matr_conf

0   1
0  21   0
1   0  22

In [10]:
# colonnes => prediction
# lignes => realité
# Composition de la matrice de confusion
true_pos_rl = matr_conf[1][1]
false_neg_rl = matr_conf[0][1]
true_neg_rl = matr_conf[0][0]
false_pos_rl = matr_conf[1][0]
true_pos_rl, true_neg_rl, false_pos_rl, false_neg_rl

(22, 21, 0, 0)

### Taux de succès : probabilité de bon classement du modèle

### Sensibilité : capacité du modèle à retrouver les positifs

### Précision : proportion de vrais positifs parmi les individus classés positifs

### Spécificité : proportion de négatifs détectés

In [11]:
# Taux de succès : probabilité de bon classement du modèle
print('Taux de succès:',metrics.accuracy_score(y_test, y_pred))

#Précision : proportion de vrais positifs parmi les individus classés positifs
print("Précision:",metrics.precision_score(y_test, y_pred))


#Sensibilité : capacité du modèle à retrouver les positifs
print("Rappel ou Sensibilité:",metrics.recall_score(y_test, y_pred))

Taux de succès: 1.0
Précision: 1.0
Rappel ou Sensibilité: 1.0


In [12]:
print("Spécificité:",true_neg_rl/(true_neg_rl + false_pos_rl))


Spécificité: 1.0


In [13]:
y_pred_train = reg_log.predict(x_train)
y_pred_train

array([False, False,  True,  True,  True,  True, False, False,  True,
        True, False,  True,  True, False,  True, False,  True,  True,
        True,  True, False,  True, False,  True,  True, False,  True,
        True, False,  True,  True, False,  True,  True, False, False,
        True,  True,  True, False, False, False, False,  True,  True,
        True, False,  True,  True, False,  True,  True,  True, False,
       False,  True, False, False, False,  True,  True,  True, False,
        True,  True,  True, False,  True,  True,  True,  True, False,
       False,  True, False,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
        True,  True, False, False,  True,  True, False, False,  True,
        True,  True,  True,  True, False,  True, False,  True, False,
       False, False,  True,  True,  True,  True,  True,  True, False,
        True, False, False, False,  True,  True,  True,  True, False,
        True])

In [14]:
print('Accuracy:',metrics.accuracy_score(y_train, y_pred_train))

print("Precision:",metrics.precision_score(y_train, y_pred_train))

print("Recall:",metrics.recall_score(y_train, y_pred_train))

Accuracy: 0.9763779527559056
Precision: 0.9746835443037974
Recall: 0.9871794871794872


In [15]:
y_pred_proba = reg_log.predict_proba(x_test)
y_pred_proba

array([[0.95570143, 0.04429857],
       [0.96053293, 0.03946707],
       [0.00999394, 0.99000606],
       [0.00532387, 0.99467613],
       [0.99675593, 0.00324407],
       [0.9238214 , 0.0761786 ],
       [0.92498639, 0.07501361],
       [0.88595461, 0.11404539],
       [0.02724263, 0.97275737],
       [0.96759035, 0.03240965],
       [0.00451778, 0.99548222],
       [0.04066638, 0.95933362],
       [0.04992634, 0.95007366],
       [0.78401091, 0.21598909],
       [0.19385545, 0.80614455],
       [0.97988559, 0.02011441],
       [0.09476251, 0.90523749],
       [0.95608536, 0.04391464],
       [0.01440383, 0.98559617],
       [0.90174186, 0.09825814],
       [0.06523884, 0.93476116],
       [0.9907046 , 0.0092954 ],
       [0.99463131, 0.00536869],
       [0.57551968, 0.42448032],
       [0.98694187, 0.01305813],
       [0.07985808, 0.92014192],
       [0.92334125, 0.07665875],
       [0.02654441, 0.97345559],
       [0.00863483, 0.99136517],
       [0.01099291, 0.98900709],
       [0.

In [16]:
# Exemple d'application du modèle de prédiction

In [17]:
example = pd.read_csv("test_notes.csv")
example

diagonal  height_left  height_right  margin_low  margin_up  length   id
0    172.09       103.95        103.73        4.39       3.09  113.19  B_1
1    171.52       104.17        104.03        5.27       3.16  111.82  B_2
2    171.78       103.80        103.75        3.81       3.24  113.39  B_3
3    172.02       104.08        103.99        5.57       3.30  111.10  B_4
4    171.79       104.34        104.37        5.00       3.07  111.87  B_5

In [18]:
id_billets = data.columns.drop('is_genuine')
x_example = example[id_billets].values

y_predict_example = reg_log.predict(x_example)

In [19]:
#Ajout du resultat
example['is_genuine'] = y_predict_example

In [20]:
#Calcul des probas d'affectaion sur l'ech. à prédire
probas = reg_log.predict_proba(x_example)

example['Probas_faux'] = probas[:,0]
example['Probas_vrais'] = probas[:,1]
example

diagonal  height_left  height_right  margin_low  margin_up  length   id  \
0    172.09       103.95        103.73        4.39       3.09  113.19  B_1   
1    171.52       104.17        104.03        5.27       3.16  111.82  B_2   
2    171.78       103.80        103.75        3.81       3.24  113.39  B_3   
3    172.02       104.08        103.99        5.57       3.30  111.10  B_4   
4    171.79       104.34        104.37        5.00       3.07  111.87  B_5   

   is_genuine  Probas_faux  Probas_vrais  
0        True     0.050036      0.949964  
1       False     0.913481      0.086519  
2        True     0.009181      0.990819  
3       False     0.991990      0.008010  
4       False     0.879828      0.120172

In [21]:
#Restriction sur vrais et les faux billets
vrais_billets = example[example['is_genuine'] == True]
faux_billets = example[example['is_genuine'] == False]

In [22]:
#Impression des identifiants des vrais billets et de leurs probalités
a1 = ['Le billet ' + str(vrais_billets.iloc[i,6]) +
      ' serait un vrai car il a une probabilité de ' +
      str(vrais_billets.iloc[i,9]) for i in range(vrais_billets.shape[0])]
for j in range(vrais_billets.shape[0]):
    print(a1[j])

Le billet B_1 serait un vrai car il a une probabilité de 0.949964367096677
Le billet B_3 serait un vrai car il a une probabilité de 0.990818605111455


In [23]:
#Impression des identifiants des vrais billets et de leurs probalités
a1 = ['Le billet ' + str(faux_billets.iloc[i,6]) +
      ' serait un faux car il a une probabilité de ' +
      str(faux_billets.iloc[i,8]) for i in range(faux_billets.shape[0])]
for j in range(faux_billets.shape[0]):
    print(a1[j])

Le billet B_2 serait un faux car il a une probabilité de 0.9134813072683526
Le billet B_4 serait un faux car il a une probabilité de 0.9919904688590473
Le billet B_5 serait un faux car il a une probabilité de 0.8798281918713882
